### PR TITLE
Implemented Reports Feature.

### PR DESCRIPTION
**Pull request by YaroslavKSE**
Implemented Reports Feature. Now api can operate with POST request. User can provide metrics and user id's and then UserReportResource is going to generate report by selecting the information about the user from the database. After that a user can make GET request with the previously stated report name in post request. The get request will return all the information which was asked about the user in a structured way. Created supporting methods in sql. Covered the code with integration, e2e, unit tests.

### CODE REVIEW

**Review by Mat203 — APPROVED** [review]
Great program with nice code, great coverage of unit, integration and E2E tests and appropriate structure

**Review by podkolzzzin — APPROVED** [review]

**Review by smazepaa — APPROVED** [review]
clearly written code, all the requirements are met and good test coverage

**Review by kmirik999 — APPROVED** [review]
interesting implementation, tests are covered well, "Report" functionality is implemented

**Comment by LevkoBe** [comment]
Very high quality! And I love the structure: it's clear, logical and easy to follow.

**Pull request merged**
